name: Build and Deploy Astro via FTP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy files via FTP
        run: |
          lftp -e "mirror -R dist /www && bye" -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
